version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - db