name: ETL
on:
  schedule:
    - cron: '0 0 * * 0'  # semanal: domingo medianoche UTC

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python etl/weekly_load.py